import { PartnershipStatus } from '@prisma/client';

export const schools = [
    {
        id: 'school_hk_primary_1',
        schoolName: '香港第一小學',
        schoolNameEn: 'Hong Kong Primary School No.1',
        schoolCode: 'HKPS001',
        address: '香港島中西區堅道123號',
        phone: '2123 4567',
        email: 'info@hkps1.edu.hk',
        partnershipStatus: PartnershipStatus.ACTIVE,
        partnershipStartDate: new Date('2024-09-01'),
        partnershipStartYear: '2024-2025',
        contacts: [
            {
                nameChinese: '陳大文',
                nameEnglish: 'Chan Tai Man',
                position: '體育科主任',
                phone: '2123 4567',
                mobile: '9123 4567',
                email: 'chan@hkps1.edu.hk',
                isPrimary: true,
            },
        ],
    },
    {
        id: 'school_kowloon_sec_1',
        schoolName: '九龍第二中學',
        schoolNameEn: 'Kowloon Secondary School No.2',
        schoolCode: 'KLSS002',
        address: '九龍油尖旺區彌敦道456號',
        phone: '2234-5678',
        email: 'info@klss2.edu.hk',
        partnershipStatus: PartnershipStatus.CONFIRMED,
        partnershipStartDate: new Date('2025-01-15'),
        partnershipStartYear: '2024-2025',
        contacts: [
            {
                nameChinese: '李小明',
                nameEnglish: 'Lee Siu Ming',
                position: '課外活動主任',
                phone: '2234-5678',
                mobile: '9234-5678',
                email: 'lee@klss2.edu.hk',
                isPrimary: true,
            },
        ],
    },
    {
        id: 'school_nt_primary_3',
        schoolName: '新界第三小學',
        schoolNameEn: 'New Territories Primary School No.3',
        schoolCode: 'NTPS003',
        address: '新界沙田區大圍道789號',
        phone: '2345-6789',
        email: 'info@ntps3.edu.hk',
        partnershipStatus: PartnershipStatus.INQUIRY,
        contacts: [
            {
                nameChinese: '王美玲',
                nameEnglish: 'Wong Mei Ling',
                position: '校長',
                phone: '2345-6789',
                mobile: '9345-6789',
                email: 'wong@ntps3.edu.hk',
                isPrimary: true,
            },
        ],
    },
    {
        id: 'school_004',
        schoolName: '聖保羅小學',
        schoolNameEn: 'St. Paul\'s Primary School',
        schoolCode: 'SPPS004',
        address: '香港島中西區般咸道68號',
        phone: '2546-1234',
        email: 'info@spps.edu.hk',
        partnershipStatus: PartnershipStatus.ACTIVE,
        partnershipStartDate: new Date('2024-09-01'),
        partnershipStartYear: '2024-2025',
        contacts: [
            {
                nameChinese: '張校長',
                nameEnglish: 'Cheung Principal',
                position: '校長',
                phone: '2546-1234',
                mobile: '9876-5432',
                email: 'cheung@spps.edu.hk',
                isPrimary: true,
            },
        ],
    },
    {
        id: 'school_005',
        schoolName: '培正小學',
        schoolNameEn: 'Pui Ching Primary School',
        schoolCode: 'PCPS005',
        address: '九龍何文田培正道20號',
        phone: '2711-9222',
        email: 'info@pcps.edu.hk',
        partnershipStatus: PartnershipStatus.ACTIVE,
        partnershipStartDate: new Date('2024-09-01'),
        partnershipStartYear: '2024-2025',
        contacts: [
            {
                nameChinese: '林主任',
                nameEnglish: 'Lam Director',
                position: '體育主任',
                phone: '2711-9222',
                mobile: '9123-8765',
                email: 'lam@pcps.edu.hk',
                isPrimary: true,
            },
        ],
    },
    {
        id: 'school_006',
        schoolName: '喇沙小學',
        schoolNameEn: 'La Salle Primary School',
        schoolCode: 'LSPS006',
        address: '九龍九龍塘喇沙利道1號',
        phone: '2336-2609',
        email: 'info@lsps.edu.hk',
        partnershipStatus: PartnershipStatus.ACTIVE,
        partnershipStartDate: new Date('2024-07-01'),
        partnershipStartYear: '2024-2025',
        contacts: [
            {
                nameChinese: '黃老師',
                nameEnglish: 'Wong Teacher',
                position: '課外活動統籌',
                phone: '2336-2609',
                mobile: '9234-5678',
                email: 'wong@lsps.edu.hk',
                isPrimary: true,
            },
        ],
    },
    {
        id: 'school_007',
        schoolName: '拔萃男書院',
        schoolNameEn: 'Diocesan Boys\' School',
        schoolCode: 'DBS007',
        address: '九龍旺角亞皆老街131號',
        phone: '2711-5191',
        email: 'info@dbs.edu.hk',
        partnershipStatus: PartnershipStatus.ACTIVE,
        partnershipStartDate: new Date('2024-10-01'),
        partnershipStartYear: '2024-2025',
        contacts: [
            {
                nameChinese: '劉教練',
                nameEnglish: 'Lau Coach',
                position: '體育部主管',
                phone: '2711-5191',
                mobile: '9345-6789',
                email: 'lau@dbs.edu.hk',
                isPrimary: true,
            },
        ],
    },
    {
        id: 'school_008',
        schoolName: '瑪利諾修院學校',
        schoolNameEn: 'Maryknoll Convent School',
        schoolCode: 'MCS008',
        address: '九龍九龍塘窩打老道130號',
        phone: '2336-2378',
        email: 'info@mcs.edu.hk',
        partnershipStatus: PartnershipStatus.CONFIRMED,
        partnershipStartDate: new Date('2025-02-01'),
        partnershipStartYear: '2024-2025',
        contacts: [
            {
                nameChinese: '陳老師',
                nameEnglish: 'Chan Teacher',
                position: '活動統籌',
                phone: '2336-2378',
                mobile: '9456-7890',
                email: 'chan@mcs.edu.hk',
                isPrimary: true,
            },
        ],
    },
    {
        id: 'school_009',
        schoolName: '聖若瑟小學',
        schoolNameEn: 'St. Joseph\'s Primary School',
        schoolCode: 'SJPS009',
        address: '香港灣仔活道48號',
        phone: '2574-5216',
        email: 'info@sjps.edu.hk',
        partnershipStatus: PartnershipStatus.ACTIVE,
        partnershipStartDate: new Date('2024-09-01'),
        partnershipStartYear: '2024-2025',
        contacts: [
            {
                nameChinese: '李主任',
                nameEnglish: 'Lee Director',
                position: '課外活動主任',
                phone: '2574-5216',
                mobile: '9567-8901',
                email: 'lee@sjps.edu.hk',
                isPrimary: true,
            },
        ],
    },
    {
        id: 'school_010',
        schoolName: '英華小學',
        schoolNameEn: 'Ying Wa Primary School',
        schoolCode: 'YWPS010',
        address: '九龍深水埗英華街1號',
        phone: '2728-3320',
        email: 'info@ywps.edu.hk',
        partnershipStatus: PartnershipStatus.TERMINATED,
        partnershipStartDate: new Date('2024-09-01'),
        partnershipStartYear: '2024-2025',
        contacts: [
            {
                nameChinese: '梁校長',
                nameEnglish: 'Leung Principal',
                position: '校長',
                phone: '2728-3320',
                mobile: '9678-9012',
                email: 'leung@ywps.edu.hk',
                isPrimary: true,
            },
        ],
    },
    {
        id: 'school_011',
        schoolName: '九龍塘學校',
        schoolNameEn: 'Kowloon Tong School',
        schoolCode: 'KTS011',
        address: '九龍九龍塘金巴倫道2721號',
        phone: '2336-0206',
        email: 'info@kts.edu.hk',
        partnershipStatus: PartnershipStatus.SUSPENDED,
        partnershipStartDate: new Date('2024-09-01'),
        partnershipStartYear: '2024-2025',
        contacts: [
            {
                nameChinese: '吳主任',
                nameEnglish: 'Ng Director',
                position: '體育主任',
                phone: '2336-0206',
                mobile: '9789-0123',
                email: 'ng@kts.edu.hk',
                isPrimary: true,
            },
        ],
    },
    {
        id: 'school_012',
        schoolName: '協恩中學',
        schoolNameEn: 'Heep Yunn School',
        schoolCode: 'HYS012',
        address: '九龍九龍城農圃道1號',
        phone: '2711-0862',
        email: 'info@hys.edu.hk',
        partnershipStatus: PartnershipStatus.CONFIRMED,
        partnershipStartDate: new Date('2025-09-01'),
        partnershipStartYear: '2025-2026',
        contacts: [
            {
                nameChinese: '鄭老師',
                nameEnglish: 'Cheng Teacher',
                position: '課外活動主任',
                phone: '2711-0862',
                mobile: '9890-1234',
                email: 'cheng@hys.edu.hk',
                isPrimary: true,
            },
        ],
    },
    {
        id: 'school_013',
        schoolName: '保良局蔡繼有學校',
        schoolNameEn: 'Po Leung Kuk Choi Kai Yau School',
        schoolCode: 'PLKCKY013',
        address: '九龍深水埗郝德傑道6號',
        phone: '2148-2052',
        email: 'info@plkcky.edu.hk',
        partnershipStatus: PartnershipStatus.ACTIVE,
        partnershipStartDate: new Date('2025-02-01'),
        partnershipStartYear: '2024-2025',
        contacts: [
            {
                nameChinese: '何主任',
                nameEnglish: 'Ho Director',
                position: '體育科主任',
                phone: '2148-2052',
                mobile: '9901-2345',
                email: 'ho@plkcky.edu.hk',
                isPrimary: true,
            },
        ],
    },
    {
        id: 'school_014',
        schoolName: '聖士提反女子中學',
        schoolNameEn: 'St. Stephen\'s Girls\' College',
        schoolCode: 'SSGC014',
        address: '香港島中西區列堤頓道2號',
        phone: '2540-5372',
        email: 'info@ssgc.edu.hk',
        partnershipStatus: PartnershipStatus.ACTIVE,
        partnershipStartDate: new Date('2024-09-15'),
        partnershipStartYear: '2024-2025',
        contacts: [
            {
                nameChinese: '譚教練',
                nameEnglish: 'Tam Coach',
                position: '校隊教練',
                phone: '2540-5372',
                mobile: '9012-3456',
                email: 'tam@ssgc.edu.hk',
                isPrimary: true,
            },
        ],
    },
    {
        id: 'school_015',
        schoolName: '華仁書院',
        schoolNameEn: 'Wah Yan College',
        schoolCode: 'WYC015',
        address: '香港島灣仔皇后大道東281號',
        phone: '2572-6217',
        email: 'info@wyc.edu.hk',
        partnershipStatus: PartnershipStatus.ACTIVE,
        partnershipStartDate: new Date('2024-09-01'),
        partnershipStartYear: '2024-2025',
        contacts: [
            {
                nameChinese: '葉老師',
                nameEnglish: 'Yip Teacher',
                position: '體育老師',
                phone: '2572-6217',
                mobile: '9123-4567',
                email: 'yip@wyc.edu.hk',
                isPrimary: true,
            },
        ],
    },
];

export function getSchoolsList() {
    return schools.map(school => ({
        id: school.id,
        schoolName: school.schoolName,
    }));
}
